"""
Demo emails for Smart Inbox - diverse set of emails for classification demonstration
"""

DEMO_EMAILS = [
    # === WORK/BUSINESS EMAILS (will be classified as work) ===
    {
        "gmail_id": "work_1",
        "subject": "Weekly Team Standup - Sprint Planning",
        "sender": "pm@techcorp.com",
        "sender_name": "Sarah Johnson",
        "snippet": "Hi team, please join our weekly standup meeting tomorrow at 10 AM to discuss sprint goals...",
        "body": "Hi team,\n\nPlease join our weekly standup meeting tomorrow at 10 AM.\n\nAgenda:\n- Sprint review\n- Blockers discussion\n- Next sprint planning\n\nMeeting link: https://meet.google.com/abc-defg-hij\n\nBest,\nSarah",
        "is_read": False,
    },
    {
        "gmail_id": "work_2",
        "subject": "Q4 Performance Review Scheduled",
        "sender": "hr@company.com",
        "sender_name": "HR Department",
        "snippet": "Your quarterly performance review has been scheduled for next week...",
        "body": "Dear Employee,\n\nYour Q4 performance review has been scheduled.\n\nDate: December 20, 2024\nTime: 2:00 PM\nLocation: Conference Room B\n\nPlease prepare your self-assessment document.\n\nRegards,\nHR Team",
        "is_read": False,
    },
    {
        "gmail_id": "work_3",
        "subject": "URGENT: Client Presentation Tomorrow",
        "sender": "director@business.com",
        "sender_name": "Michael Chen",
        "snippet": "The client presentation has been moved to tomorrow morning. Please review the deck...",
        "body": "Team,\n\nImportant update: The client presentation has been rescheduled to tomorrow at 9 AM.\n\nAction items:\n1. Review the presentation deck\n2. Prepare talking points\n3. Test the demo environment\n\nThis is high priority.\n\nMichael",
        "is_read": False,
    },
    {
        "gmail_id": "work_4",
        "subject": "New Project Assignment: Mobile App Redesign",
        "sender": "lead@startup.io",
        "sender_name": "Tech Lead",
        "snippet": "You've been assigned to the mobile app redesign project starting next week...",
        "body": "Hi,\n\nYou've been selected for the mobile app redesign project.\n\nProject Details:\n- Duration: 3 months\n- Team size: 5 developers\n- Stack: React Native, Node.js\n\nKickoff meeting: Monday 10 AM\n\nLet me know if you have questions.",
        "is_read": True,
    },
    {
        "gmail_id": "work_5",
        "subject": "Invoice #INV-2024-1234 - Payment Due",
        "sender": "billing@vendor.com",
        "sender_name": "Accounts Receivable",
        "snippet": "Please find attached invoice for services rendered in November...",
        "body": "Dear Customer,\n\nPlease find attached Invoice #INV-2024-1234.\n\nAmount Due: $2,500.00\nDue Date: December 30, 2024\n\nPayment methods accepted:\n- Bank transfer\n- Credit card\n\nThank you for your business.",
        "is_read": True,
    },
    
    # === SOCIAL MEDIA NOTIFICATIONS ===
    {
        "gmail_id": "social_1",
        "subject": "John liked your photo",
        "sender": "notification@facebook.com",
        "sender_name": "Facebook",
        "snippet": "John Smith and 15 others liked your photo from last weekend...",
        "body": "John Smith liked your photo.\n\n15 others also liked this photo.\n\nView your photo and comments on Facebook.",
        "is_read": True,
    },
    {
        "gmail_id": "social_2",
        "subject": "@techguru mentioned you in a tweet",
        "sender": "notify@twitter.com",
        "sender_name": "Twitter",
        "snippet": "@techguru: Great article by @you about web development trends...",
        "body": "@techguru mentioned you:\n\n\"Great article by @you about web development trends! Everyone should read this. 🔥\"\n\nView the conversation on Twitter.",
        "is_read": False,
    },
    {
        "gmail_id": "social_3",
        "subject": "You have 5 new connection requests",
        "sender": "messages@linkedin.com",
        "sender_name": "LinkedIn",
        "snippet": "Recruiters from Google, Microsoft, and 3 others want to connect...",
        "body": "You have new connection requests:\n\n1. Jane Doe - Recruiter at Google\n2. Bob Smith - HR Manager at Microsoft\n3. Alice Johnson - Tech Lead at Amazon\n\nExpand your network on LinkedIn.",
        "is_read": True,
    },
    {
        "gmail_id": "social_4",
        "subject": "New follower on Instagram",
        "sender": "no-reply@instagram.com",
        "sender_name": "Instagram",
        "snippet": "photography_lover started following you on Instagram...",
        "body": "photography_lover started following you.\n\nThey have 5,234 followers and post about travel and photography.\n\nCheck out their profile on Instagram.",
        "is_read": True,
    },
    
    # === PROMOTIONS & MARKETING ===
    {
        "gmail_id": "promo_1",
        "subject": "🎉 50% OFF Everything - Black Friday Extended!",
        "sender": "deals@amazon.com",
        "sender_name": "Amazon",
        "snippet": "Don't miss our biggest sale of the year! Limited time offer...",
        "body": "BLACK FRIDAY EXTENDED!\n\n50% OFF on:\n- Electronics\n- Home & Kitchen\n- Fashion\n- Books\n\nUse code: FRIDAY50\n\nOffer ends Sunday midnight!\n\nShop now at amazon.com",
        "is_read": True,
    },
    {
        "gmail_id": "promo_2",
        "subject": "Your Spotify Wrapped 2024 is here! 🎵",
        "sender": "no-reply@spotify.com",
        "sender_name": "Spotify",
        "snippet": "See your top songs, artists, and listening habits from 2024...",
        "body": "Your 2024 Wrapped is ready!\n\nYour top artist: Taylor Swift\nMinutes listened: 45,678\nTop genre: Pop\n\nShare your Wrapped with friends!\n\nDiscover your complete listening story.",
        "is_read": False,
    },
    {
        "gmail_id": "promo_3",
        "subject": "Free shipping on your next order!",
        "sender": "newsletter@shop.com",
        "sender_name": "Fashion Store",
        "snippet": "Use code FREESHIP for free delivery on orders over $50...",
        "body": "FREE SHIPPING WEEKEND!\n\nUse code: FREESHIP\nMinimum order: $50\nValid until: Sunday\n\nNew arrivals:\n- Winter collection\n- Holiday specials\n- Gift sets\n\nShop now!",
        "is_read": True,
    },
    {
        "gmail_id": "promo_4",
        "subject": "Last chance: Your cart is expiring",
        "sender": "reminder@store.com",
        "sender_name": "Online Store",
        "snippet": "You left items in your cart. Complete your purchase before they sell out...",
        "body": "Don't forget!\n\nYou have 3 items in your cart:\n- Wireless Headphones ($99)\n- Phone Case ($29)\n- USB-C Cable ($15)\n\nTotal: $143\n\nComplete your order now - items are selling fast!",
        "is_read": False,
    },
    
    # === UPDATES & NOTIFICATIONS ===
    {
        "gmail_id": "update_1",
        "subject": "Security Alert: New sign-in to your account",
        "sender": "security@google.com",
        "sender_name": "Google",
        "snippet": "We noticed a new sign-in to your Google Account from a Windows device...",
        "body": "New sign-in detected\n\nDevice: Windows PC\nLocation: Istanbul, Turkey\nTime: Today at 3:45 PM\n\nIf this was you, you can ignore this message.\nIf not, secure your account immediately.",
        "is_read": False,
    },
    {
        "gmail_id": "update_2",
        "subject": "Your order has shipped! 📦",
        "sender": "orders@amazon.com",
        "sender_name": "Amazon Shipping",
        "snippet": "Great news! Your order is on its way. Track your package...",
        "body": "Your order has shipped!\n\nOrder #123-456-789\nEstimated delivery: Dec 18-20\n\nItems:\n- Wireless Mouse\n- Keyboard\n\nTrack your package: [tracking link]",
        "is_read": True,
    },
    {
        "gmail_id": "update_3",
        "subject": "Password changed successfully",
        "sender": "noreply@github.com",
        "sender_name": "GitHub",
        "snippet": "Your GitHub password was changed. If you didn't make this change...",
        "body": "Password Changed\n\nYour password was successfully changed on December 15, 2024.\n\nIf you didn't make this change, please reset your password immediately and contact support.",
        "is_read": True,
    },
    {
        "gmail_id": "update_4",
        "subject": "Your flight is confirmed ✈️",
        "sender": "booking@airline.com",
        "sender_name": "Turkish Airlines",
        "snippet": "Your flight TK1234 to London is confirmed for December 22...",
        "body": "Flight Confirmation\n\nFlight: TK1234\nFrom: Istanbul (IST)\nTo: London (LHR)\nDate: December 22, 2024\nTime: 10:30 AM\n\nCheck-in opens 24 hours before departure.",
        "is_read": False,
    },
    
    # === PERSONAL EMAILS ===
    {
        "gmail_id": "personal_1",
        "subject": "Dinner tonight?",
        "sender": "bestfriend@gmail.com",
        "sender_name": "Emma Wilson",
        "snippet": "Hey! Are you free for dinner tonight? There's a new Italian place...",
        "body": "Hey!\n\nAre you free for dinner tonight? There's a new Italian place downtown that everyone's been talking about.\n\nLet me know! 🍝\n\nEmma",
        "is_read": False,
    },
    {
        "gmail_id": "personal_2",
        "subject": "Photos from the trip",
        "sender": "friend@yahoo.com",
        "sender_name": "Alex Martinez",
        "snippet": "Here are the photos from our weekend getaway! Had such a great time...",
        "body": "Hey!\n\nFinally uploaded all the photos from our trip. You can view them here: [Google Photos link]\n\nWe should definitely do this again soon!\n\nAlex",
        "is_read": True,
    },
    {
        "gmail_id": "personal_3",
        "subject": "Happy Birthday! 🎂",
        "sender": "mom@email.com",
        "sender_name": "Mom",
        "snippet": "Happy birthday sweetheart! Wishing you all the best on your special day...",
        "body": "Happy Birthday!\n\nWishing you a wonderful day filled with joy and happiness. Can't wait to celebrate with you this weekend!\n\nLove always,\nMom ❤️",
        "is_read": False,
    },
    
    # === NEWSLETTERS ===
    {
        "gmail_id": "news_1",
        "subject": "Weekly Tech Digest: Top Stories",
        "sender": "digest@technews.com",
        "sender_name": "Tech Weekly",
        "snippet": "This week: New iPhone features, Tesla updates, and more...",
        "body": "TECH WEEKLY DIGEST\n\nTop Stories:\n1. Apple announces new iPhone features\n2. Tesla's latest update breaks records\n3. Google's new search algorithm\n4. Microsoft's cloud gaming expansion\n\nRead more on our website.",
        "is_read": True,
    },
    {
        "gmail_id": "news_2",
        "subject": "Your Morning Briefing",
        "sender": "news@dailydigest.com",
        "sender_name": "Daily Digest",
        "snippet": "Today's top headlines and weather forecast for your area...",
        "body": "GOOD MORNING!\n\nToday's Headlines:\n- Global markets reach new highs\n- Climate summit concludes with agreement\n- Sports: Champions League results\n\nWeather: Partly cloudy, 15°C\n\nHave a great day!",
        "is_read": True,
    },
    
    # === FINANCE ===
    {
        "gmail_id": "finance_1",
        "subject": "Your monthly statement is ready",
        "sender": "statements@bank.com",
        "sender_name": "City Bank",
        "snippet": "Your December statement is now available. Log in to view...",
        "body": "Monthly Statement Available\n\nYour December 2024 statement is ready.\n\nAccount ending: ****4567\nStatement period: Dec 1-31, 2024\n\nLog in to your account to view details.",
        "is_read": True,
    },
    {
        "gmail_id": "finance_2",
        "subject": "Payment received - Thank you!",
        "sender": "payments@service.com",
        "sender_name": "Payment Confirmation",
        "snippet": "We've received your payment of $49.99 for your subscription...",
        "body": "Payment Confirmed\n\nAmount: $49.99\nService: Premium Subscription\nDate: December 15, 2024\n\nThank you for your payment!",
        "is_read": True,
    },
    
    # === MORE WORK EMAILS ===
    {
        "gmail_id": "work_6",
        "subject": "Code Review Request: Feature Branch",
        "sender": "notifications@github.com",
        "sender_name": "GitHub",
        "snippet": "teammate requested your review on Pull Request #142...",
        "body": "Review Requested\n\nPR #142: Add user authentication\nBy: @teammate\n\nChanges:\n- JWT implementation\n- Login/logout endpoints\n- Unit tests\n\nReview and approve.",
        "is_read": False,
    },
    {
        "gmail_id": "work_7",
        "subject": "Meeting Rescheduled: Project Kickoff",
        "sender": "calendar@company.com",
        "sender_name": "Calendar",
        "snippet": "The project kickoff meeting has been moved to Thursday...",
        "body": "Meeting Update\n\nOriginal: Wednesday 2 PM\nNew time: Thursday 10 AM\nRoom: Conference Room A\n\nAgenda:\n1. Project overview\n2. Team introductions\n3. Timeline review",
        "is_read": True,
    },
    {
        "gmail_id": "work_8",
        "subject": "Slack: New message in #general",
        "sender": "notification@slack.com",
        "sender_name": "Slack",
        "snippet": "You have new messages in the #general channel...",
        "body": "New messages in #general\n\n@manager: Team meeting in 5 minutes!\n@colleague: Don't forget to submit your timesheets.\n\nView in Slack.",
        "is_read": True,
    },
]

